version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_USER: marketadmin
      POSTGRES_PASSWORD: psswrd
      POSTGRES_DB: authmarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
